### ISSUE TITLE
port number collision between latest one-number branches

### ISSUE THREAD

**Issue by chris-mair** [PGBuildFarm/client-code#12]
Hi,

I guess this line is in need of an update with the new single number revision scheme:

https://github.com/PGBuildFarm/client-code/blob/6d26211975955c2580f97b73bed69206ac5a8da0/run_build.pl#L214

as it is now, HEAD and REL_10_STABLE will use the same port.

Bye,
Chris.

**Comment by adunstan** [comment]
Fixed in commit 4bdd48a. Thanks for the report.
