### ISSUE TITLE
Incorrect check for wait_timeout watchdog in the END block

### ISSUE THREAD

**Issue by vbwagner** [PGBuildFarm/client-code#13]
In the END block of run_build.pl first line seems to be intended to check whether this block is run from man process (and have to delete working directory) or from wait_timeout watchdog (and have to do nothing).

` return if (defined($waiter_pid) && $waiter_pid == $$);`

Unfortunately, $waiter_pid variable is never defined in waiter process. It is assigned only in main process to the pid of child (waiter) process after the fork. So END block is unable to tell waiter process from main process without defined wait_timeout.

So, if job is terminated via wait_timeout,  two processes attempt to recursive remove working directory and prroduce a lot of error messages about suddenly disappearted files they wamted to remove.

This line should read

`retiurn if $main_pid == $$;`

Variable $main_pid is always defined (just above END block)  so it is of no use to check its existense.

**Comment by adunstan** [comment]
I don't think that's the right fix. The right fix is to define $waiter_pid in the waiter. That done in commit 89456b7
