### ISSUE TITLE
libsepol INFO messages 

### ISSUE THREAD

**Issue by jconway** [PGBuildFarm/client-code#16]
Sometime in the past year the cleanup for TestSepgsql.pm started emitting a message to stdout for every run.

This seems to be because of a change in libsepol which affects this command: "semodule -r sepgsql-regtest". I looked at the underlying source and there seems to be no way to silence the INFO message. See:
  libsemanage/src/direct_api.c:semanage_direct_remove_key
and
  libsepol/src/debug.c

I have locally applied the following patch:
----------------
*** PGBuild/Modules/TestSepgsql.pm.orig 2018-08-23 12:50:15.303314923 -0700
--- PGBuild/Modules/TestSepgsql.pm      2018-08-23 12:53:14.608369668 -0700
***************
*** 250,256 ****

        print time_str(), "cleaning up ", __PACKAGE__, "\n" if $verbose > 1;

!       system("sudo semodule -r sepgsql-regtest");
        return;
  }

--- 250,256 ----

        print time_str(), "cleaning up ", __PACKAGE__, "\n" if $verbose > 1;

!       system("sudo semodule -r sepgsql-regtest > /dev/null");
        return;
  }

Please consider doing this, or whatever you consider to be the proper fix.

**Comment by adunstan** [comment]
Fixed in 09f34736cde4
