### ISSUE TITLE
Improve handling if https://buildfarm.postgresql.org/branches_of_interest.txt can't be fetched

### ISSUE THREAD

**Issue by anarazel** [PGBuildFarm/client-code#17]
Occasionally https://buildfarm.postgresql.org/branches_of_interest.txt can't be fetched (say because the machine is rebooted), and then everyone gets a bunch of spam from cron because
```
        die "getting branches of interest ($url)" unless $branches_of_interest;
```

At the very least the error message should be better, but it'd be even better if we could use a stale file, or retry after a delay, or ...

**Comment by adunstan** [comment]
improved in commit 7a1a8f0
