### ISSUE TITLE
OpenBSD - print kern.version

### ISSUE THREAD

**Issue by jungle-boogie** [PGBuildFarm/client-code#18]
Hi All,

From my build:
https://buildfarm.postgresql.org/cgi-bin/show_log.pl?nm=scorpionfly&dt=2019-08-28%2019%3A00%3A06

Problem is that the `uname -v` information is practically useless on OpenBSD:
```
uname -m = amd64
uname -r = 6.6
uname -s = OpenBSD
uname -v = GENERIC.MP#257
```

I think it would be a good idea to get the sysctl kern.version information:

```
$ sysctl kern.version
kern.version=OpenBSD 6.6-beta (GENERIC.MP) #257: Wed Aug 28 09:12:29 MDT 2019
    deraadt@amd64.openbsd.org:/usr/src/sys/arch/amd64/compile/GENERIC.MP
```

`#257` doesn't really mean anything at all: https://flak.tedunangst.com/post/OpenBSD-version-numbers

`This number is a archaic remnant of long ago. It is mostly useless. For instance, a bug report that specifies “kernel number 27” means little. `

I realize this may not be necessary for building Postgresql, but it'll provide a little more information about the animal.

**Comment by adunstan** [comment]
This use of `uname` isn't coming from the buildfarm. It's  called by Postgres' `configure`, so you should make this suggestion to the core project.
