### ISSUE TITLE
Feature request: Command / Flag to see if any branch needs to run test

### ISSUE THREAD

**Issue by anarazel** [PGBuildFarm/client-code#25]
Hi,

I've started to run buildfarm iterations via systemd timers. That allows only running run_branches.pl when it's not already running (with a time difference since the last run, rather than some regular timer), contains an animal into a cgroup, shows resource usage of runs etc.

I'd like to put an ExecCondition so that the whole service doesn't even get started if there's nothing to do. Maybe something like run_branches.pl needed? I've also wanted to know this before, interactively.

Insane?

Thanks,

Andres

**Comment by adunstan** [comment]
Is the recent commit b5be57b sufficient for your needs, or do you want more?

**Comment by anarazel** [comment]
It definitely is less "urgent" now. I think it'd still be useful though.

**Comment by adunstan** [comment]
Have a look and see if the patch above does what you want.
