### ISSUE TITLE
Use ExtUtils::MakeMaker or EUMM to package for CPAN

### ISSUE THREAD

**Issue by ringerc** [PGBuildFarm/client-code#3]
If ExtUtils::MakeMaker, EUMM, or (deprecated) Module::Build are used, then dependencies can be instaled directly from CPAN with a simple `perl -f Makefile.PL` and `make install`.

This would be a lot nicer when configuring machines as buildfarm members, especially when making the config automatable over ansible or similar.

**Comment by adunstan** [comment]
This wasn't designed to use these modules, and our file layout is a bit different from what EUMM requires. If you can provide me with a patch I'll look at it. Otherwise I'll close the item.

**Comment by adunstan** [comment]
no progress so closing.
