### ISSUE TITLE
Environment filtering in meson builds causes problems with sanitizers

### ISSUE THREAD

**Issue by anarazel** [PGBuildFarm/client-code#31]
Hi,

Currently one needs to include at least detect_leaks=0 and detect_stack_use_after_return=0 in ASAN_OPTIONS to have a build succeed. I just updated my buildfarm instance, and suddenly the relevant animals failed. Caused by `_meson_env()` filtering out the ASAN_OPTIONS I had set in the build farm configuration's `build_env`.  I temporarily patched my installation, but that doesn't seem like the right fix...

Why are the environment options filtered at all?  And, if they need to be, shouldn't at least options set in build_env be included in `_meson_env()`?

Greetings,

Andres

**Comment by adunstan** [comment]
There have been complaints in the past that we were leaking information from the owner's environment. That's why we filter the settings in several places. But commit e2dd439 does allow all the build_env settings.

**Comment by anarazel** [comment]
Thanks!
