### ISSUE TITLE
Rename build-farm.conf to build-farm.conf.template

### ISSUE THREAD

**Issue by ringerc** [PGBuildFarm/client-code#4]
It'd be useful if the repo renamed `build-farm.conf` to `build-farm.conf.template` and added `build-farm.conf` to `.gitignore`. That makes it nicer to work with the config file in-tree.

Probably not a big deal given that there's a `--config` parameter to the client, of course.

**Comment by adunstan** [comment]
renamed to .sample in commit cea1ec55d9cd9d8ac44cf40c9ff955b8fda586
