### ISSUE TITLE
Clone the builder's own logs into lastbuild-logs

### ISSUE THREAD

**Issue by ringerc** [PGBuildFarm/client-code#5]
It's hard to tell why the build failed before generating a status stamp file when doing a `--test` run; the builder's own logs don't get recorded into the lastbuild-logs dir.

It looks like the point at which the build failed is only recorded as `$stage` in `web-txn.data`.

Whether in verbose mode or not, it'd be nice to output the builder's own logs to the log dir to make it easier to tell what's going on when working on a build worker.

(I'm noting this mainly as a task for myself).

**Comment by adunstan** [comment]
What are you looking for other than the SCM log? We could write that out as soon as the checkout returns. It would be blown away and recreated when we redo the logs, but if something failed in between that would preserve it. We don't really do anything else much of significance before that.

**Comment by adunstan** [comment]
No progress, so closing.
