### ISSUE TITLE
Problem with ActivePerl 5.22 on Windows.

### ISSUE THREAD

**Issue by vbwagner** [PGBuildFarm/client-code#8]
I've discovered following problem with recent ActivePerl on Windows:
run_build.pl fails on the Git stage with message 
"ssh cannot resolve host c"
Error occurs when repository is cloned from
$config->{buildroot}/pgmirror.git to working repository,
It seems that windows Git from git-scm.com doesn't properly understand windows paths with forward slashes like
&lt;drive&gt;:/&lt;directory&gt;
and interprets them like &lt;host&gt;:/path. 
It does however interpret such paths with backslashes 
&lt;drive&gt;:\&lt;directory&gt;
correctly.
It looks like behavoir of abspath function is changed in the recent ActivePerl (which is now compiled with mingw).

I've fixed this problem by adding regexp which replaces forward slashers for backslashes just before a clone command if source url looks like \w:/

**Comment by adunstan** [comment]
I am unable to reproduce this, using perl 5.24 and a recent git installed via choco.
